<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetBase.Service\NetBase.Service.csproj" />
    <ProjectReference Include="..\NetBase.Middleware\NetBase.Middleware.csproj" />
    <ProjectReference Include="..\NetBase.Model\NetBase.Model.csproj" />
    <ProjectReference Include="..\NetBase.Common\NetBase.Common.csproj" />
  </ItemGroup>

</Project>
